// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/dariamoshkina/gopherMart/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// MockBalanceService is an autogenerated mock type for the BalanceService type
type MockBalanceService struct {
	mock.Mock
}

type MockBalanceService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBalanceService) EXPECT() *MockBalanceService_Expecter {
	return &MockBalanceService_Expecter{mock: &_m.Mock}
}

// GetBalance provides a mock function with given fields: ctx, userID
func (_m *MockBalanceService) GetBalance(ctx context.Context, userID int64) (*model.Balance, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetBalance")
	}

	var r0 *model.Balance
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*model.Balance, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *model.Balance); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Balance)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBalanceService_GetBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBalance'
type MockBalanceService_GetBalance_Call struct {
	*mock.Call
}

// GetBalance is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *MockBalanceService_Expecter) GetBalance(ctx interface{}, userID interface{}) *MockBalanceService_GetBalance_Call {
	return &MockBalanceService_GetBalance_Call{Call: _e.mock.On("GetBalance", ctx, userID)}
}

func (_c *MockBalanceService_GetBalance_Call) Run(run func(ctx context.Context, userID int64)) *MockBalanceService_GetBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockBalanceService_GetBalance_Call) Return(_a0 *model.Balance, _a1 error) *MockBalanceService_GetBalance_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBalanceService_GetBalance_Call) RunAndReturn(run func(context.Context, int64) (*model.Balance, error)) *MockBalanceService_GetBalance_Call {
	_c.Call.Return(run)
	return _c
}

// ListWithdrawals provides a mock function with given fields: ctx, userID
func (_m *MockBalanceService) ListWithdrawals(ctx context.Context, userID int64) ([]*model.Withdrawal, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListWithdrawals")
	}

	var r0 []*model.Withdrawal
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]*model.Withdrawal, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []*model.Withdrawal); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Withdrawal)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBalanceService_ListWithdrawals_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListWithdrawals'
type MockBalanceService_ListWithdrawals_Call struct {
	*mock.Call
}

// ListWithdrawals is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *MockBalanceService_Expecter) ListWithdrawals(ctx interface{}, userID interface{}) *MockBalanceService_ListWithdrawals_Call {
	return &MockBalanceService_ListWithdrawals_Call{Call: _e.mock.On("ListWithdrawals", ctx, userID)}
}

func (_c *MockBalanceService_ListWithdrawals_Call) Run(run func(ctx context.Context, userID int64)) *MockBalanceService_ListWithdrawals_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockBalanceService_ListWithdrawals_Call) Return(_a0 []*model.Withdrawal, _a1 error) *MockBalanceService_ListWithdrawals_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBalanceService_ListWithdrawals_Call) RunAndReturn(run func(context.Context, int64) ([]*model.Withdrawal, error)) *MockBalanceService_ListWithdrawals_Call {
	_c.Call.Return(run)
	return _c
}

// Withdraw provides a mock function with given fields: ctx, userID, orderNumber, sum
func (_m *MockBalanceService) Withdraw(ctx context.Context, userID int64, orderNumber string, sum int64) error {
	ret := _m.Called(ctx, userID, orderNumber, sum)

	if len(ret) == 0 {
		panic("no return value specified for Withdraw")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, int64) error); ok {
		r0 = rf(ctx, userID, orderNumber, sum)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockBalanceService_Withdraw_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Withdraw'
type MockBalanceService_Withdraw_Call struct {
	*mock.Call
}

// Withdraw is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - orderNumber string
//   - sum int64
func (_e *MockBalanceService_Expecter) Withdraw(ctx interface{}, userID interface{}, orderNumber interface{}, sum interface{}) *MockBalanceService_Withdraw_Call {
	return &MockBalanceService_Withdraw_Call{Call: _e.mock.On("Withdraw", ctx, userID, orderNumber, sum)}
}

func (_c *MockBalanceService_Withdraw_Call) Run(run func(ctx context.Context, userID int64, orderNumber string, sum int64)) *MockBalanceService_Withdraw_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(string), args[3].(int64))
	})
	return _c
}

func (_c *MockBalanceService_Withdraw_Call) Return(_a0 error) *MockBalanceService_Withdraw_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBalanceService_Withdraw_Call) RunAndReturn(run func(context.Context, int64, string, int64) error) *MockBalanceService_Withdraw_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockBalanceService creates a new instance of MockBalanceService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBalanceService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBalanceService {
	mock := &MockBalanceService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
