// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/dariamoshkina/gopherMart/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// MockOrdersService is an autogenerated mock type for the OrdersService type
type MockOrdersService struct {
	mock.Mock
}

type MockOrdersService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrdersService) EXPECT() *MockOrdersService_Expecter {
	return &MockOrdersService_Expecter{mock: &_m.Mock}
}

// ListOrders provides a mock function with given fields: ctx, userID
func (_m *MockOrdersService) ListOrders(ctx context.Context, userID int64) ([]*model.Order, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListOrders")
	}

	var r0 []*model.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]*model.Order, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []*model.Order); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrdersService_ListOrders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListOrders'
type MockOrdersService_ListOrders_Call struct {
	*mock.Call
}

// ListOrders is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *MockOrdersService_Expecter) ListOrders(ctx interface{}, userID interface{}) *MockOrdersService_ListOrders_Call {
	return &MockOrdersService_ListOrders_Call{Call: _e.mock.On("ListOrders", ctx, userID)}
}

func (_c *MockOrdersService_ListOrders_Call) Run(run func(ctx context.Context, userID int64)) *MockOrdersService_ListOrders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockOrdersService_ListOrders_Call) Return(_a0 []*model.Order, _a1 error) *MockOrdersService_ListOrders_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrdersService_ListOrders_Call) RunAndReturn(run func(context.Context, int64) ([]*model.Order, error)) *MockOrdersService_ListOrders_Call {
	_c.Call.Return(run)
	return _c
}

// SubmitOrder provides a mock function with given fields: ctx, userID, orderNumber
func (_m *MockOrdersService) SubmitOrder(ctx context.Context, userID int64, orderNumber string) error {
	ret := _m.Called(ctx, userID, orderNumber)

	if len(ret) == 0 {
		panic("no return value specified for SubmitOrder")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string) error); ok {
		r0 = rf(ctx, userID, orderNumber)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOrdersService_SubmitOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SubmitOrder'
type MockOrdersService_SubmitOrder_Call struct {
	*mock.Call
}

// SubmitOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - orderNumber string
func (_e *MockOrdersService_Expecter) SubmitOrder(ctx interface{}, userID interface{}, orderNumber interface{}) *MockOrdersService_SubmitOrder_Call {
	return &MockOrdersService_SubmitOrder_Call{Call: _e.mock.On("SubmitOrder", ctx, userID, orderNumber)}
}

func (_c *MockOrdersService_SubmitOrder_Call) Run(run func(ctx context.Context, userID int64, orderNumber string)) *MockOrdersService_SubmitOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(string))
	})
	return _c
}

func (_c *MockOrdersService_SubmitOrder_Call) Return(_a0 error) *MockOrdersService_SubmitOrder_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOrdersService_SubmitOrder_Call) RunAndReturn(run func(context.Context, int64, string) error) *MockOrdersService_SubmitOrder_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOrdersService creates a new instance of MockOrdersService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrdersService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrdersService {
	mock := &MockOrdersService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
