// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/dariamoshkina/gopherMart/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// MockBalanceRepository is an autogenerated mock type for the BalanceRepository type
type MockBalanceRepository struct {
	mock.Mock
}

type MockBalanceRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBalanceRepository) EXPECT() *MockBalanceRepository_Expecter {
	return &MockBalanceRepository_Expecter{mock: &_m.Mock}
}

// Credit provides a mock function with given fields: ctx, userID, amount
func (_m *MockBalanceRepository) Credit(ctx context.Context, userID int64, amount int64) error {
	ret := _m.Called(ctx, userID, amount)

	if len(ret) == 0 {
		panic("no return value specified for Credit")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) error); ok {
		r0 = rf(ctx, userID, amount)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockBalanceRepository_Credit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Credit'
type MockBalanceRepository_Credit_Call struct {
	*mock.Call
}

// Credit is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - amount int64
func (_e *MockBalanceRepository_Expecter) Credit(ctx interface{}, userID interface{}, amount interface{}) *MockBalanceRepository_Credit_Call {
	return &MockBalanceRepository_Credit_Call{Call: _e.mock.On("Credit", ctx, userID, amount)}
}

func (_c *MockBalanceRepository_Credit_Call) Run(run func(ctx context.Context, userID int64, amount int64)) *MockBalanceRepository_Credit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64))
	})
	return _c
}

func (_c *MockBalanceRepository_Credit_Call) Return(_a0 error) *MockBalanceRepository_Credit_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBalanceRepository_Credit_Call) RunAndReturn(run func(context.Context, int64, int64) error) *MockBalanceRepository_Credit_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUserID provides a mock function with given fields: ctx, userID
func (_m *MockBalanceRepository) GetByUserID(ctx context.Context, userID int64) (*model.Balance, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByUserID")
	}

	var r0 *model.Balance
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*model.Balance, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *model.Balance); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Balance)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBalanceRepository_GetByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUserID'
type MockBalanceRepository_GetByUserID_Call struct {
	*mock.Call
}

// GetByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *MockBalanceRepository_Expecter) GetByUserID(ctx interface{}, userID interface{}) *MockBalanceRepository_GetByUserID_Call {
	return &MockBalanceRepository_GetByUserID_Call{Call: _e.mock.On("GetByUserID", ctx, userID)}
}

func (_c *MockBalanceRepository_GetByUserID_Call) Run(run func(ctx context.Context, userID int64)) *MockBalanceRepository_GetByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockBalanceRepository_GetByUserID_Call) Return(_a0 *model.Balance, _a1 error) *MockBalanceRepository_GetByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBalanceRepository_GetByUserID_Call) RunAndReturn(run func(context.Context, int64) (*model.Balance, error)) *MockBalanceRepository_GetByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrCreate provides a mock function with given fields: ctx, userID
func (_m *MockBalanceRepository) GetOrCreate(ctx context.Context, userID int64) (*model.Balance, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetOrCreate")
	}

	var r0 *model.Balance
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*model.Balance, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *model.Balance); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Balance)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBalanceRepository_GetOrCreate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrCreate'
type MockBalanceRepository_GetOrCreate_Call struct {
	*mock.Call
}

// GetOrCreate is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *MockBalanceRepository_Expecter) GetOrCreate(ctx interface{}, userID interface{}) *MockBalanceRepository_GetOrCreate_Call {
	return &MockBalanceRepository_GetOrCreate_Call{Call: _e.mock.On("GetOrCreate", ctx, userID)}
}

func (_c *MockBalanceRepository_GetOrCreate_Call) Run(run func(ctx context.Context, userID int64)) *MockBalanceRepository_GetOrCreate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockBalanceRepository_GetOrCreate_Call) Return(_a0 *model.Balance, _a1 error) *MockBalanceRepository_GetOrCreate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBalanceRepository_GetOrCreate_Call) RunAndReturn(run func(context.Context, int64) (*model.Balance, error)) *MockBalanceRepository_GetOrCreate_Call {
	_c.Call.Return(run)
	return _c
}

// ListWithdrawalsByUserID provides a mock function with given fields: ctx, userID
func (_m *MockBalanceRepository) ListWithdrawalsByUserID(ctx context.Context, userID int64) ([]*model.Withdrawal, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListWithdrawalsByUserID")
	}

	var r0 []*model.Withdrawal
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]*model.Withdrawal, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []*model.Withdrawal); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Withdrawal)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBalanceRepository_ListWithdrawalsByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListWithdrawalsByUserID'
type MockBalanceRepository_ListWithdrawalsByUserID_Call struct {
	*mock.Call
}

// ListWithdrawalsByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *MockBalanceRepository_Expecter) ListWithdrawalsByUserID(ctx interface{}, userID interface{}) *MockBalanceRepository_ListWithdrawalsByUserID_Call {
	return &MockBalanceRepository_ListWithdrawalsByUserID_Call{Call: _e.mock.On("ListWithdrawalsByUserID", ctx, userID)}
}

func (_c *MockBalanceRepository_ListWithdrawalsByUserID_Call) Run(run func(ctx context.Context, userID int64)) *MockBalanceRepository_ListWithdrawalsByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockBalanceRepository_ListWithdrawalsByUserID_Call) Return(_a0 []*model.Withdrawal, _a1 error) *MockBalanceRepository_ListWithdrawalsByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBalanceRepository_ListWithdrawalsByUserID_Call) RunAndReturn(run func(context.Context, int64) ([]*model.Withdrawal, error)) *MockBalanceRepository_ListWithdrawalsByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// Withdraw provides a mock function with given fields: ctx, userID, orderNumber, sum
func (_m *MockBalanceRepository) Withdraw(ctx context.Context, userID int64, orderNumber string, sum int64) error {
	ret := _m.Called(ctx, userID, orderNumber, sum)

	if len(ret) == 0 {
		panic("no return value specified for Withdraw")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, int64) error); ok {
		r0 = rf(ctx, userID, orderNumber, sum)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockBalanceRepository_Withdraw_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Withdraw'
type MockBalanceRepository_Withdraw_Call struct {
	*mock.Call
}

// Withdraw is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - orderNumber string
//   - sum int64
func (_e *MockBalanceRepository_Expecter) Withdraw(ctx interface{}, userID interface{}, orderNumber interface{}, sum interface{}) *MockBalanceRepository_Withdraw_Call {
	return &MockBalanceRepository_Withdraw_Call{Call: _e.mock.On("Withdraw", ctx, userID, orderNumber, sum)}
}

func (_c *MockBalanceRepository_Withdraw_Call) Run(run func(ctx context.Context, userID int64, orderNumber string, sum int64)) *MockBalanceRepository_Withdraw_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(string), args[3].(int64))
	})
	return _c
}

func (_c *MockBalanceRepository_Withdraw_Call) Return(_a0 error) *MockBalanceRepository_Withdraw_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBalanceRepository_Withdraw_Call) RunAndReturn(run func(context.Context, int64, string, int64) error) *MockBalanceRepository_Withdraw_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockBalanceRepository creates a new instance of MockBalanceRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBalanceRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBalanceRepository {
	mock := &MockBalanceRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
