// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	model "github.com/dariamoshkina/gopherMart/internal/model"

	mock "github.com/stretchr/testify/mock"
)

// MockBalanceRepository is an autogenerated mock type for the BalanceRepository type
type MockBalanceRepository struct {
	mock.Mock
}

// Credit provides a mock function with given fields: ctx, userID, amount
func (_m *MockBalanceRepository) Credit(ctx context.Context, userID int64, amount int64) error {
	ret := _m.Called(ctx, userID, amount)

	if len(ret) == 0 {
		panic("no return value specified for Credit")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) error); ok {
		r0 = rf(ctx, userID, amount)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByUserID provides a mock function with given fields: ctx, userID
func (_m *MockBalanceRepository) GetByUserID(ctx context.Context, userID int64) (*model.Balance, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByUserID")
	}

	var r0 *model.Balance
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*model.Balance, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *model.Balance); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Balance)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOrCreate provides a mock function with given fields: ctx, userID
func (_m *MockBalanceRepository) GetOrCreate(ctx context.Context, userID int64) (*model.Balance, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetOrCreate")
	}

	var r0 *model.Balance
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*model.Balance, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *model.Balance); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Balance)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListWithdrawalsByUserID provides a mock function with given fields: ctx, userID
func (_m *MockBalanceRepository) ListWithdrawalsByUserID(ctx context.Context, userID int64) ([]*model.Withdrawal, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListWithdrawalsByUserID")
	}

	var r0 []*model.Withdrawal
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]*model.Withdrawal, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []*model.Withdrawal); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Withdrawal)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Withdraw provides a mock function with given fields: ctx, userID, orderNumber, sum
func (_m *MockBalanceRepository) Withdraw(ctx context.Context, userID int64, orderNumber string, sum int64) error {
	ret := _m.Called(ctx, userID, orderNumber, sum)

	if len(ret) == 0 {
		panic("no return value specified for Withdraw")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, int64) error); ok {
		r0 = rf(ctx, userID, orderNumber, sum)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockBalanceRepository creates a new instance of MockBalanceRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBalanceRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBalanceRepository {
	mock := &MockBalanceRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
