// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/dariamoshkina/gopherMart/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// MockOrderRepository is an autogenerated mock type for the OrderRepository type
type MockOrderRepository struct {
	mock.Mock
}

type MockOrderRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrderRepository) EXPECT() *MockOrderRepository_Expecter {
	return &MockOrderRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, userID, orderNumber
func (_m *MockOrderRepository) Create(ctx context.Context, userID int64, orderNumber string) (*model.Order, error) {
	ret := _m.Called(ctx, userID, orderNumber)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *model.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string) (*model.Order, error)); ok {
		return rf(ctx, userID, orderNumber)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, string) *model.Order); ok {
		r0 = rf(ctx, userID, orderNumber)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, string) error); ok {
		r1 = rf(ctx, userID, orderNumber)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrderRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockOrderRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - orderNumber string
func (_e *MockOrderRepository_Expecter) Create(ctx interface{}, userID interface{}, orderNumber interface{}) *MockOrderRepository_Create_Call {
	return &MockOrderRepository_Create_Call{Call: _e.mock.On("Create", ctx, userID, orderNumber)}
}

func (_c *MockOrderRepository_Create_Call) Run(run func(ctx context.Context, userID int64, orderNumber string)) *MockOrderRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(string))
	})
	return _c
}

func (_c *MockOrderRepository_Create_Call) Return(_a0 *model.Order, _a1 error) *MockOrderRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrderRepository_Create_Call) RunAndReturn(run func(context.Context, int64, string) (*model.Order, error)) *MockOrderRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByOrderNumber provides a mock function with given fields: ctx, orderNumber
func (_m *MockOrderRepository) GetByOrderNumber(ctx context.Context, orderNumber string) (*model.Order, error) {
	ret := _m.Called(ctx, orderNumber)

	if len(ret) == 0 {
		panic("no return value specified for GetByOrderNumber")
	}

	var r0 *model.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.Order, error)); ok {
		return rf(ctx, orderNumber)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Order); ok {
		r0 = rf(ctx, orderNumber)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, orderNumber)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrderRepository_GetByOrderNumber_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByOrderNumber'
type MockOrderRepository_GetByOrderNumber_Call struct {
	*mock.Call
}

// GetByOrderNumber is a helper method to define mock.On call
//   - ctx context.Context
//   - orderNumber string
func (_e *MockOrderRepository_Expecter) GetByOrderNumber(ctx interface{}, orderNumber interface{}) *MockOrderRepository_GetByOrderNumber_Call {
	return &MockOrderRepository_GetByOrderNumber_Call{Call: _e.mock.On("GetByOrderNumber", ctx, orderNumber)}
}

func (_c *MockOrderRepository_GetByOrderNumber_Call) Run(run func(ctx context.Context, orderNumber string)) *MockOrderRepository_GetByOrderNumber_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockOrderRepository_GetByOrderNumber_Call) Return(_a0 *model.Order, _a1 error) *MockOrderRepository_GetByOrderNumber_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrderRepository_GetByOrderNumber_Call) RunAndReturn(run func(context.Context, string) (*model.Order, error)) *MockOrderRepository_GetByOrderNumber_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUserID provides a mock function with given fields: ctx, userID
func (_m *MockOrderRepository) GetByUserID(ctx context.Context, userID int64) ([]*model.Order, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByUserID")
	}

	var r0 []*model.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]*model.Order, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []*model.Order); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrderRepository_GetByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUserID'
type MockOrderRepository_GetByUserID_Call struct {
	*mock.Call
}

// GetByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *MockOrderRepository_Expecter) GetByUserID(ctx interface{}, userID interface{}) *MockOrderRepository_GetByUserID_Call {
	return &MockOrderRepository_GetByUserID_Call{Call: _e.mock.On("GetByUserID", ctx, userID)}
}

func (_c *MockOrderRepository_GetByUserID_Call) Run(run func(ctx context.Context, userID int64)) *MockOrderRepository_GetByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockOrderRepository_GetByUserID_Call) Return(_a0 []*model.Order, _a1 error) *MockOrderRepository_GetByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrderRepository_GetByUserID_Call) RunAndReturn(run func(context.Context, int64) ([]*model.Order, error)) *MockOrderRepository_GetByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// GetPending provides a mock function with given fields: ctx, limit
func (_m *MockOrderRepository) GetPending(ctx context.Context, limit int) ([]*model.Order, error) {
	ret := _m.Called(ctx, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetPending")
	}

	var r0 []*model.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]*model.Order, error)); ok {
		return rf(ctx, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []*model.Order); ok {
		r0 = rf(ctx, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrderRepository_GetPending_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPending'
type MockOrderRepository_GetPending_Call struct {
	*mock.Call
}

// GetPending is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
func (_e *MockOrderRepository_Expecter) GetPending(ctx interface{}, limit interface{}) *MockOrderRepository_GetPending_Call {
	return &MockOrderRepository_GetPending_Call{Call: _e.mock.On("GetPending", ctx, limit)}
}

func (_c *MockOrderRepository_GetPending_Call) Run(run func(ctx context.Context, limit int)) *MockOrderRepository_GetPending_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockOrderRepository_GetPending_Call) Return(_a0 []*model.Order, _a1 error) *MockOrderRepository_GetPending_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrderRepository_GetPending_Call) RunAndReturn(run func(context.Context, int) ([]*model.Order, error)) *MockOrderRepository_GetPending_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatus provides a mock function with given fields: ctx, orderID, status, accrual
func (_m *MockOrderRepository) UpdateStatus(ctx context.Context, orderID int64, status string, accrual *int64) error {
	ret := _m.Called(ctx, orderID, status, accrual)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, *int64) error); ok {
		r0 = rf(ctx, orderID, status, accrual)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOrderRepository_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type MockOrderRepository_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID int64
//   - status string
//   - accrual *int64
func (_e *MockOrderRepository_Expecter) UpdateStatus(ctx interface{}, orderID interface{}, status interface{}, accrual interface{}) *MockOrderRepository_UpdateStatus_Call {
	return &MockOrderRepository_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", ctx, orderID, status, accrual)}
}

func (_c *MockOrderRepository_UpdateStatus_Call) Run(run func(ctx context.Context, orderID int64, status string, accrual *int64)) *MockOrderRepository_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(string), args[3].(*int64))
	})
	return _c
}

func (_c *MockOrderRepository_UpdateStatus_Call) Return(_a0 error) *MockOrderRepository_UpdateStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOrderRepository_UpdateStatus_Call) RunAndReturn(run func(context.Context, int64, string, *int64) error) *MockOrderRepository_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOrderRepository creates a new instance of MockOrderRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderRepository {
	mock := &MockOrderRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
