// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/dariamoshkina/gopherMart/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// MockOrderRepo is an autogenerated mock type for the OrderRepo type
type MockOrderRepo struct {
	mock.Mock
}

type MockOrderRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrderRepo) EXPECT() *MockOrderRepo_Expecter {
	return &MockOrderRepo_Expecter{mock: &_m.Mock}
}

// GetPending provides a mock function with given fields: ctx, limit
func (_m *MockOrderRepo) GetPending(ctx context.Context, limit int) ([]*model.Order, error) {
	ret := _m.Called(ctx, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetPending")
	}

	var r0 []*model.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]*model.Order, error)); ok {
		return rf(ctx, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []*model.Order); ok {
		r0 = rf(ctx, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrderRepo_GetPending_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPending'
type MockOrderRepo_GetPending_Call struct {
	*mock.Call
}

// GetPending is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
func (_e *MockOrderRepo_Expecter) GetPending(ctx interface{}, limit interface{}) *MockOrderRepo_GetPending_Call {
	return &MockOrderRepo_GetPending_Call{Call: _e.mock.On("GetPending", ctx, limit)}
}

func (_c *MockOrderRepo_GetPending_Call) Run(run func(ctx context.Context, limit int)) *MockOrderRepo_GetPending_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockOrderRepo_GetPending_Call) Return(_a0 []*model.Order, _a1 error) *MockOrderRepo_GetPending_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrderRepo_GetPending_Call) RunAndReturn(run func(context.Context, int) ([]*model.Order, error)) *MockOrderRepo_GetPending_Call {
	_c.Call.Return(run)
	return _c
}

// MarkProcessedWithCredit provides a mock function with given fields: ctx, orderID, userID, accrual
func (_m *MockOrderRepo) MarkProcessedWithCredit(ctx context.Context, orderID int64, userID int64, accrual *int64) error {
	ret := _m.Called(ctx, orderID, userID, accrual)

	if len(ret) == 0 {
		panic("no return value specified for MarkProcessedWithCredit")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64, *int64) error); ok {
		r0 = rf(ctx, orderID, userID, accrual)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOrderRepo_MarkProcessedWithCredit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkProcessedWithCredit'
type MockOrderRepo_MarkProcessedWithCredit_Call struct {
	*mock.Call
}

// MarkProcessedWithCredit is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID int64
//   - userID int64
//   - accrual *int64
func (_e *MockOrderRepo_Expecter) MarkProcessedWithCredit(ctx interface{}, orderID interface{}, userID interface{}, accrual interface{}) *MockOrderRepo_MarkProcessedWithCredit_Call {
	return &MockOrderRepo_MarkProcessedWithCredit_Call{Call: _e.mock.On("MarkProcessedWithCredit", ctx, orderID, userID, accrual)}
}

func (_c *MockOrderRepo_MarkProcessedWithCredit_Call) Run(run func(ctx context.Context, orderID int64, userID int64, accrual *int64)) *MockOrderRepo_MarkProcessedWithCredit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64), args[3].(*int64))
	})
	return _c
}

func (_c *MockOrderRepo_MarkProcessedWithCredit_Call) Return(_a0 error) *MockOrderRepo_MarkProcessedWithCredit_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOrderRepo_MarkProcessedWithCredit_Call) RunAndReturn(run func(context.Context, int64, int64, *int64) error) *MockOrderRepo_MarkProcessedWithCredit_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatus provides a mock function with given fields: ctx, orderID, status, accrual
func (_m *MockOrderRepo) UpdateStatus(ctx context.Context, orderID int64, status string, accrual *int64) error {
	ret := _m.Called(ctx, orderID, status, accrual)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, *int64) error); ok {
		r0 = rf(ctx, orderID, status, accrual)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOrderRepo_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type MockOrderRepo_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID int64
//   - status string
//   - accrual *int64
func (_e *MockOrderRepo_Expecter) UpdateStatus(ctx interface{}, orderID interface{}, status interface{}, accrual interface{}) *MockOrderRepo_UpdateStatus_Call {
	return &MockOrderRepo_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", ctx, orderID, status, accrual)}
}

func (_c *MockOrderRepo_UpdateStatus_Call) Run(run func(ctx context.Context, orderID int64, status string, accrual *int64)) *MockOrderRepo_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(string), args[3].(*int64))
	})
	return _c
}

func (_c *MockOrderRepo_UpdateStatus_Call) Return(_a0 error) *MockOrderRepo_UpdateStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOrderRepo_UpdateStatus_Call) RunAndReturn(run func(context.Context, int64, string, *int64) error) *MockOrderRepo_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOrderRepo creates a new instance of MockOrderRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderRepo {
	mock := &MockOrderRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
