// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	accrual "github.com/dariamoshkina/gopherMart/internal/client/accrual"
	mock "github.com/stretchr/testify/mock"
)

// MockAccrualClient is an autogenerated mock type for the AccrualClient type
type MockAccrualClient struct {
	mock.Mock
}

type MockAccrualClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAccrualClient) EXPECT() *MockAccrualClient_Expecter {
	return &MockAccrualClient_Expecter{mock: &_m.Mock}
}

// GetOrder provides a mock function with given fields: ctx, orderNumber
func (_m *MockAccrualClient) GetOrder(ctx context.Context, orderNumber string) (*accrual.AccrualResult, error) {
	ret := _m.Called(ctx, orderNumber)

	if len(ret) == 0 {
		panic("no return value specified for GetOrder")
	}

	var r0 *accrual.AccrualResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*accrual.AccrualResult, error)); ok {
		return rf(ctx, orderNumber)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *accrual.AccrualResult); ok {
		r0 = rf(ctx, orderNumber)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*accrual.AccrualResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, orderNumber)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAccrualClient_GetOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrder'
type MockAccrualClient_GetOrder_Call struct {
	*mock.Call
}

// GetOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - orderNumber string
func (_e *MockAccrualClient_Expecter) GetOrder(ctx interface{}, orderNumber interface{}) *MockAccrualClient_GetOrder_Call {
	return &MockAccrualClient_GetOrder_Call{Call: _e.mock.On("GetOrder", ctx, orderNumber)}
}

func (_c *MockAccrualClient_GetOrder_Call) Run(run func(ctx context.Context, orderNumber string)) *MockAccrualClient_GetOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAccrualClient_GetOrder_Call) Return(_a0 *accrual.AccrualResult, _a1 error) *MockAccrualClient_GetOrder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAccrualClient_GetOrder_Call) RunAndReturn(run func(context.Context, string) (*accrual.AccrualResult, error)) *MockAccrualClient_GetOrder_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAccrualClient creates a new instance of MockAccrualClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAccrualClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAccrualClient {
	mock := &MockAccrualClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
